export const ProductData = [
    {
      id: 1,
      name: "AMD Ryzen 7 7700 Budget Gaming Desktop PC",
      price: 49999,
      productCode: 6545154,
      eistmatatedProce: 54900,
      status: "In Stock",
      image: "/images/pc/agon-pro-ag276q.webp",
      brand: "AMD",
      keyFeatures: [
        { model: "AMD Ryzen 7 7700 Budget Gaming Desktop PC" },
        { processor: "AMD Ryzen 7 7700" },
        { ram: "16GB DDR4 RAM" },
        { storage: "1TB SSD + 2TB HDD" },
        { graphics: "NVIDIA GeForce GTX 1070 Ti" },
        { display: "17.3-inch FHD IPS" },
        { warranty: "1 Year Warranty" },
      ],
      description: `The AMD Ryzen 7 7700 Budget Gaming Desktop PC is engineered to deliver exceptional performance for both gamers and content creators. Featuring 8 cores and 16 threads, the Ryzen 7 7700 ensures smooth multitasking and rapid processing speeds. Paired with a reliable B650M motherboard, 16GB high-speed DDR4 RAM, and a dual-storage setup (1TB SSD for fast boot times and 2TB HDD for mass storage), this PC provides a balanced blend of speed and capacity. The NVIDIA GTX 1070 Ti graphics card enables high-quality 1080p gaming, making it ideal for esports and AAA titles. Whether you're gaming, streaming, or editing, this desktop is designed to keep up with your demands.`
    },
    {
      id: 2,
      name: "Intel Core i5 12400F Budget Gaming Desktop",
      price: 42999,
      productCode: 6589412,
      eistmatatedProce: 46900,
      status: "In Stock",
      image: "/images/pc/amd-ryzen-5.webp",
      brand: "Intel",
      keyFeatures: [
        { model: "Intel Core i5 12400F Gaming Desktop" },
        { processor: "Intel Core i5 12400F" },
        { ram: "16GB DDR4 RAM" },
        { storage: "512GB SSD" },
        { graphics: "GTX 1660 Super" },
        { display: "N/A" },
        { warranty: "1 Year Warranty" },
      ],
      description: `Designed for budget-conscious gamers, the Intel Core i5 12400F Desktop PC combines affordability with impressive performance. The 6-core CPU delivers reliable power for gaming, streaming, and productivity. Featuring a GTX 1660 Super graphics card, this PC can run most modern games at medium to high settings. Its 512GB SSD ensures fast boot and application load times. A stylish mid-tower case with RGB lighting adds visual flair. Perfect for entry-level gamers looking for value without sacrificing performance.`
    },
    {
      id: 3,
      name: "Intel Core i7 12700K Professional PC",
      price: 74999,
      productCode: 6598412,
      eistmatatedProce: 79900,
      status: "In Stock",
      image: "/images/pc/ds-d5b65rb-el-.webp",
      brand: "Intel",
      keyFeatures: [
        { model: "Intel Core i7 12700K Professional PC" },
        { processor: "Intel Core i7 12700K" },
        { ram: "32GB DDR5 RAM" },
        { storage: "1TB NVMe SSD" },
        { graphics: "RTX 3060 Ti" },
        { display: "N/A" },
        { warranty: "3 Year Warranty" },
      ],
      description: `The Intel Core i7 12700K Professional PC is built for those who demand power and versatility. Equipped with 12 cores and 20 threads, this machine is perfect for professional workloads such as video editing, 3D rendering, and gaming. With 32GB DDR5 RAM and RTX 3060 Ti graphics, users can expect ultra-fast performance in all tasks. The 1TB NVMe SSD ensures rapid data access, and the sleek design offers excellent airflow and cable management. A future-ready choice for creators and gamers.`
    },
    {
      id: 4,
      name: "AMD Ryzen 5 5600G APU Desktop",
      price: 32999,
      productCode: 6598413,
      eistmatatedProce: 34900,
      status: "In Stock",
      image: "/images/pc/monitor.webp",
      brand: "AMD",
      keyFeatures: [
        { model: "AMD Ryzen 5 5600G APU PC" },
        { processor: "AMD Ryzen 5 5600G" },
        { ram: "16GB DDR4 RAM" },
        { storage: "512GB SSD" },
        { graphics: "Radeon Vega 7 (Integrated)" },
        { display: "N/A" },
        { warranty: "1 Year Warranty" },
      ],
      description: `A perfect budget desktop, the AMD Ryzen 5 5600G APU PC offers solid performance with integrated Radeon Vega 7 graphics. This makes it ideal for casual gaming, educational use, and office work. With 6 cores, 12 threads, and a base clock of 3.9GHz, multitasking is fluid. The system runs quietly and efficiently, making it perfect for home users or students. The compact form factor ensures easy placement in any environment.`
    },
    {
      id: 5,
      name: "Gaming Beast – Ryzen 9 7900X + RTX 4070",
      price: 159999,
      productCode: 1111101,
      eistmatatedProce: 164900,
      status: "In Stock",
      image: "/images/pc/ryzen-5-8500g-.webp",
      brand: "AMD",
      keyFeatures: [
        { model: "High-End Gaming Beast" },
        { processor: "Ryzen 9 7900X" },
        { ram: "32GB DDR5 RAM" },
        { storage: "2TB SSD + 4TB HDD" },
        { graphics: "RTX 4070 12GB" },
        { display: "N/A" },
        { warranty: "3 Year Warranty" },
      ],
      description: `Unleash unmatched performance with the Gaming Beast featuring Ryzen 9 7900X and RTX 4070. Whether you're playing AAA titles at 1440p or 4K, streaming, or editing 4K videos, this desktop does it all with ease. Loaded with 32GB high-speed DDR5 RAM and a powerful 2TB SSD, you get both speed and capacity. The RTX 4070 GPU ensures high frame rates and ray tracing capabilities. This PC is built for enthusiasts and professionals who want nothing but the best.`
    },
    {
      id: 6,
      name: "Entry-Level Student Desktop - Ryzen 3 3200G",
      price: 22999,
      productCode: 1111102,
      eistmatatedProce: 24999,
      status: "In Stock",
      image: "/images/pc/agon-pro-.webp",
      brand: "AMD",
      keyFeatures: [
        { model: "Student Desktop PC" },
        { processor: "Ryzen 3 3200G" },
        { ram: "8GB DDR4 RAM" },
        { storage: "256GB SSD" },
        { graphics: "Radeon Vega 8" },
        { display: "N/A" },
        { warranty: "1 Year Warranty" },
      ],
      description: `This Ryzen 3 3200G desktop is tailored for students and general-purpose users. With integrated Vega 8 graphics and 8GB RAM, it can handle browsing, studying, online classes, and light gaming. It’s compact, quiet, and affordable, perfect for home or dorm setups. It provides a smooth Windows experience without breaking the bank.`
    },
    {
      id: 7,
      name: "Workstation PC - Intel Xeon E5 Series",
      price: 89999,
      productCode: 1111103,
      eistmatatedProce: 95000,
      status: "In Stock",
      image: "/images/pc/ryzen-7-.webp",
      brand: "Intel",
      keyFeatures: [
        { model: "Professional Workstation" },
        { processor: "Dual Xeon E5-2680 v4" },
        { ram: "64GB DDR4 ECC RAM" },
        { storage: "1TB SSD + 4TB HDD" },
        { graphics: "Quadro P2000" },
        { display: "N/A" },
        { warranty: "3 Year Warranty" },
      ],
      description: `Built for professionals, this workstation features dual Xeon E5 CPUs for extreme multitasking and computing power. 64GB ECC RAM and Quadro graphics make it perfect for CAD, 3D modeling, simulation, and data science. It’s built like a tank, with advanced cooling and long-term stability for 24/7 usage.`
    },
    {
      id: 8,
      name: "Mini PC - Intel NUC i5 11th Gen Supper Fast",
      price: 37999,
      productCode: 1111104,
      eistmatatedProce: 39999,
      status: "In Stock",
      image: "/images//pc/1.webp",
      brand: "Intel",
      keyFeatures: [
        { model: "Intel NUC Mini PC" },
        { processor: "Intel Core i5 11th Gen" },
        { ram: "8GB DDR4 RAM" },
        { storage: "256GB SSD" },
        { graphics: "Intel Iris Xe" },
        { display: "N/A" },
        { warranty: "1 Year Warranty" },
      ],
      description: `Compact, efficient, and powerful – this Intel NUC mini PC is ideal for office users and minimalists. With Iris Xe graphics and the latest i5 CPU, it’s great for multi-monitor setups, light editing, and productivity. Perfect for those who want desktop performance in a small package.`
    },
    {
      id: 9,
      name: "All-in-One PC - 23.8\" FHD, Ryzen 5",
      price: 56999,
      productCode: 1111105,
      eistmatatedProce: 59999,
      status: "In Stock",
      image: "/images/pc/2.jpg",
      brand: "AMD",
      keyFeatures: [
        { model: "All-in-One PC" },
        { processor: "Ryzen 5 5600U" },
        { ram: "16GB DDR4 RAM" },
        { storage: "512GB SSD" },
        { graphics: "Integrated Vega" },
        { display: "23.8-inch FHD" },
        { warranty: "1 Year Warranty" },
      ],
      description: `A space-saving all-in-one PC with a stunning 23.8" FHD display. Featuring Ryzen 5 performance and 16GB RAM, it’s suitable for home, office, or educational use. The slim design looks great in any space, and with everything built-in, setup is simple and clutter-free.`
    },
    {
      id: 10,
      name: "Budget Editing PC - Intel i3 + GTX 1650",
      price: 37999,
      productCode: 1111106,
      eistmatatedProce: 40999,
      status: "In Stock",
      image: "/images/pc/3.webp",
      brand: "Intel",
      keyFeatures: [
        { model: "Editing & Gaming Budget PC" },
        { processor: "Intel Core i3 12100F" },
        { ram: "16GB DDR4 RAM" },
        { storage: "512GB SSD" },
        { graphics: "GTX 1650 4GB" },
        { display: "N/A" },
        { warranty: "1 Year Warranty" },
      ],
      description: `A perfect choice for beginner video editors and casual gamers, this PC features the latest Core i3 CPU with 4 cores and GTX 1650 graphics. It can handle Adobe Premiere Pro, Photoshop, and lightweight gaming at 1080p. Budget-friendly yet surprisingly capable for creative tasks.`
    },
  ];
  